In [1]:
import numpy as np

In [9]:
#mathematical function

#aggregation function
arr1= np.array([1,2,3,4,576,7,8])

print(np.sum(arr1))
print(np.prod(arr1))
print(np.min(arr1))
print(np.max(arr1))
print(np.argmin(arr1))#it will return minimum value ka index dikayega
print(np.argmax(arr1))

print(np.mean(arr1))
print(np.std(arr1))
print(np.median(arr1))



601
774144
1
576
0
4
85.85714285714286
200.1138451492254
4.0


In [16]:
arr1 = np.zeros((3, 4)) 
print(arr1, arr1.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4)


In [15]:

arr1 = np.arange(1,20) 
print(arr1, arr1.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] (19,)


In [22]:
arr1= np.linspace(1,10,10) 
print(arr1, arr1.shape)
print()

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] (10,)

