In [1]:
import numpy as np

In [6]:
arr2d=np.array([[1,2,3],[1,2,3],[5,6,4]])
print(arr2d)

print(np.sum(arr2d))
sum_of_coloums=np.sum(arr2d,axis=0)
print(sum_of_coloums)


sum_of_rows=np.sum(arr2d,axis=1)
print(sum_of_rows)


print(arr2d[1:3,2:3])

#slicing
print(arr3d[:,0,:])

[[1 2 3]
 [1 2 3]
 [5 6 4]]
27
[ 7 10 10]
[ 6  6 15]
[[3]
 [4]]
[[1 2 3]
 [1 2 3]]


In [10]:
arr3d=np.array([[[1,2,3],[2,4,5],[3,2,4]],[[1,2,3],[6,5,7],[4,5,6]]])
print(arr3d,arr3d.shape)
print(arr3d[:,0,:])

[[[1 2 3]
  [2 4 5]
  [3 2 4]]

 [[1 2 3]
  [6 5 7]
  [4 5 6]]] (2, 3, 3)
[[1 2 3]
 [1 2 3]]
