In [1]:
import numpy as np

In [3]:
num = np.arange(1,11)
print(num)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
num = np.zeros(10)
print(num)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
num = np.ones(10)
print(num)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [8]:
num = np.linspace(0,1,10)
print(num)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [10]:
num = np.full((3,3),7)
print(num)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [14]:
num = np.array([10,20,30,40,50])
print(num[2])

#last 2 elemetns
print(num[-1])
print(num[-2])

30
50
40


In [16]:
num = np.array([10,20,30,40,50])
print(num[ : :2])

[10 30 50]


In [28]:
#reversing a array
num = np.array([10,20,30,40,50])
print(num[len(num)::-1])

[50 40 30 20 10]


In [34]:
arr2d =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[0][1])

2


In [38]:
num = np.array([1,2,3,4,5])
print(num**5)

[   1   32  243 1024 3125]


In [39]:
#multiplying array elemnet wize
num1 = np.array([1,2,3])
num2 = np.array([4,5,6])
num1*num2

array([ 4, 10, 18])

In [40]:
num = np.array([1,2,3,4,5])
num**2

array([ 1,  4,  9, 16, 25])

In [42]:
num1 = np.array([1,2,3])
print(sum(num1))

6


In [47]:
num =np.array([10,20,30,40,50])
print(num.mean())
# num =np.array([10,20,30,40,50]).mean()
# print(num)

30.0


In [48]:
num =np.array([10,20,30,40,50,60])
reshapes = num.reshape(2,3)
print(reshapes)

[[10 20 30]
 [40 50 60]]


In [52]:
num = np.array([3,7,1,9,4])
print(num.min(),num.max())


1 9


In [57]:
num = np.array([[1,2],[2,3],[4,3]]).shape
print(num)

(3, 2)


In [61]:
num = np.array([[1,2],[2,3],[4,3]]).flatten()
print(num)
print(num.shape)

[1 2 2 3 4 3]
(6,)


In [62]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
num[num%2 ==0]

array([ 2,  4,  6,  8, 10])

In [64]:
num  = np.array([1,2,3,4,5,6,7,8,9,10])
num[num>=5]=0
num

array([1, 2, 3, 4, 0, 0, 0, 0, 0, 0])

In [68]:
num  = np.array([1,2,3,4,5,6,7,8,9,10])
print((num>5).sum())

5


In [70]:
num =np.any(np.array([1,2,3,4,5]) > 4)
print(num)

True


In [73]:
num = np.all(np.array([0,2,3,4,5]) > 0)
print(num)

False


In [75]:
marks =np.array([45,67,89,32,76])
print((marks>50).sum())

3


In [77]:
temp = np.array([30,32,29,35,31,28,33]).mean()
print(temp)


31.142857142857142


In [78]:
celci = np.array([0,20,30,40])
celci*(9//5)+32

array([32, 52, 62, 72])

In [86]:
week1 = np.array([100,200,300])
week2 = np.array([150,250,350])
week1+week2

array([250, 450, 650])