In [1]:
import numpy as np

In [3]:
num = np.arange(1,11)
print(num)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
num = np.zeros(10)
print(num)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
num = np.ones(10)
print(num)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [8]:
num = np.linspace(0,1,10)
print(num)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [10]:
num = np.full((3,3),7)
print(num)

[[7 7 7]
 [7 7 7]
 [7 7 7]]
