In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])
arr2 = np.array([1,2,3,4,5,6])
#vectorization 
print(arr+arr2)
print(arr ** 2)


[ 2  4  6  8 10 12]
[ 1  4  9 16 25 36]


In [9]:
#brodcasting 
#what does it mean
#see first it will compare the right most shapw and if they are same and then if left shape s one or less that the left of other element then there will compatable
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],[3,4,5],[2,3,4]])
print(arr1+arr2)

[[2 4 6]
 [4 6 8]
 [3 5 7]]
